global:
  scrape_interval: 30s # default 60s
  evaluation_interval: 30s # default 60s
  scrape_timeout: 5s # default 10s

  external_labels:
    monitor: "{{ ansible_hostname }}"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - prober_smartmouse.rules

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "smartmouse"
    metrics_path: "/probe"
    params:
      module: [http_head_fast_2xx]
    static_configs:
      - targets: ["https://smartmousetravel.com"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
