global:
  scrape_interval:     30s
  evaluation_interval: 30s
  scrape_timeout:      5s

  external_labels:
    monitor: 'home-monitor'

rule_files:
  - '/etc/prometheus/house.rules'
  - '/etc/prometheus/node.rules'
  - '/etc/prometheus/ups.rules'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
          {{- range service "prometheus-alertmanager-alertmanager" }}
          - '{{ .Address }}:{{ .Port }}'
          {{- end }}

scrape_configs:
  - job_name: 'router'
    static_configs:
      - targets: ['192.168.101.1:9100']
        labels:
          host: router

  - job_name: 'node'
    relabel_configs:
      - target_label: instance
        replacement: hedwig_node
    static_configs:
      - targets:
          {{- range nodes }}
          - '{{ .Address }}:9100'
          {{- end }}
        labels:
          host: hedwig

  - job_name: 'nomad'
    metrics_path: '/v1/metrics'
    params:
      format: ['prometheus']
    relabel_configs:
      - target_label: instance
        replacement: hedwig_nomad
    static_configs:
      - targets:
          {{- range nodes }}
          - '{{ .Address }}:4646'
          {{- end }}
        labels:
          host: hedwig

  - job_name: 'hass'
    metrics_path: '/api/prometheus'
    bearer_token: '{{ with secret "secret/homeassistant" }}{{ .Data.prometheus_token }}{{ end }}'
    relabel_configs:
      - target_label: instance
        replacement: homeassistant
    static_configs:
      - targets:
          {{- range service "homeassistant" }}
          - '{{ .Address }}:{{ .Port }}'
          {{- end }}

  - job_name: 'apcupsd'
    metrics_path: '/metrics'
    relabel_configs:
      - target_label: instance
        replacement: hedwig_ups
    static_configs:
      - targets:
          {{- range service "apcupsd-exporter" }}
          - '{{ .Address }}:{{ .Port }}'
          {{- end }}
