- name: Get HashiCorp upstream APT GPG key
  apt_key:
    id: '{{ hashicorp_apt_key }}'
    keyserver: 'hkp://pool.sks-keyservers.net'
    state: present

- name: Configure HashiCorp upstream APT repository
  apt_repository:
    repo: '{{ hashicorp_repository }}'
    state: present

- name: Install Consul
  apt:
    pkg: ['consul']

- name: Create Consul data directory
  file:
    path: '{{ consul_storage_directory }}'
    state: directory
    owner: consul
    group: consul
    mode: '0750'

- name: Install Consul server config
  template:
    src: consul.hcl
    dest: /etc/consul.d/
    owner: consul
    group: consul
    mode: '640'
  notify:
    - 'restart consul'
