- name: Create package download directory
  file:
    path: '{{ package_download_directory }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Consul group
  group:
    name: consul
    state: present
    system: true

- name: Create Consul user
  user:
    name: consul
    group: consul
    create_home: false
    password_lock: true
    system: true
    home: /etc/consul.d

- name: Create Consul data directory
  file:
    path: '{{ consul_storage_directory }}'
    state: directory
    owner: consul
    group: consul
    mode: '0750'

- name: Install Consul systemd service
  copy:
    src: consul.service
    dest: /etc/systemd/system
    mode: '644'
  notify:
    - 'enable consul'

- name: Fetch Consul
  get_url:
    url: '{{ consul_package.url }}'
    checksum: '{{ consul_package.sum }}'
    dest: '{{ package_download_directory }}/{{ consul_package.filename }}'

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Install Consul binary
  unarchive:
    src: '{{ package_download_directory }}/{{ consul_package.filename }}'
    dest: /usr/local/sbin
    remote_src: yes
    owner: root
    group: root
  notify:
    - 'restart consul'

- name: Install Consul server config
  template:
    src: consul.hcl
    dest: /etc/consul.d/
    owner: consul
    group: consul
    mode: '640'
  notify:
    - 'restart consul'
