---
- name: Install OpenSSH daemon config file
  ansible.builtin.template:
    src: sshd.conf
    dest: /etc/ssh/sshd_config.d/00-no-passwords.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart SSH

- name: Prepare data volume
  block:
    - name: Create the data volume filesystem
      community.general.filesystem:
        fstype: "{{ data_volume_fstype }}"
        dev: "{{ data_volume_blkdev }}"

    - name: Mount the data volume filesystem
      ansible.posix.mount:
        path: "{{ data_volume_mount_path }}"
        src: "{{ data_volume_blkdev }}"
        fstype: "{{ data_volume_fstype }}"
        state: mounted

  when: data_volume_mount_path|length > 0

- name: Get Fluent Bit APT key
  ansible.builtin.get_url:
    url: https://packages.fluentbit.io/fluentbit.key
    dest: /etc/apt/trusted.gpg.d/fluentbit.asc
    checksum: sha256:df248e2d7103ca62cb683c20a077198d0fb0a7f79dbf53a604af0317de3b4711

- name: Configure Fluent Bit APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/fluentbit.asc] https://packages.fluentbit.io/ubuntu/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install base packages
  ansible.builtin.apt:
    pkg:
      - fluent-bit
      - prometheus-node-exporter
    state: present

- name: Enable Fluent Bit service
  ansible.builtin.systemd:
    name: fluent-bit.service
    enabled: yes
    state: started

- name: Install Fluent Bit config file
  ansible.builtin.template:
    src: fluent-bit.conf
    dest: /etc/fluent-bit/fluent-bit.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Fluent Bit
