---
- name: Install OpenSSH daemon config file
  ansible.builtin.template:
    src: sshd.conf
    dest: /etc/ssh/sshd_config.d/00-no-passwords.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart SSH

- name: Prepare data volume
  block:
    - name: Create the data volume filesystem
      community.general.filesystem:
        fstype: "{{ data_volume_fstype }}"
        dev: "{{ data_volume_blkdev }}"

    - name: Mount the data volume filesystem
      ansible.posix.mount:
        path: "{{ data_volume_mount_path }}"
        src: "{{ data_volume_blkdev }}"
        fstype: "{{ data_volume_fstype }}"
        state: mounted

  when: data_volume_mount_path|length > 0

- name: Install Prometheus node stats exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
