---
prometheus_data_directory: "/var/lib/prometheus"
alertmanager_smtp_relayhost: "localhost:25"
alertmanager_smtp_from: "alertmanager@example.com"
alertmanager_pagerduty_key: ""
grafana_data_directory: "/var/lib/grafana"
grafana_instance_name: "${HOSTNAME}"
grafana_email_from: "grafana@example.com"
grafana_secret_key: "ZOMG CHANGE ME"
