network:
  ethernets:
    enp7s0:
      dhcp4: false
      addresses: ["192.168.101.2/24"]
      nameservers:
        addresses: ["75.75.75.75", "75.75.76.76"]
      routes:
        - to: "0.0.0.0/0"
          via: "192.168.101.1"
          on-link: true
  version: 2
