docker_users: ['lucas']
docker_daemon_options: []
docker_apt_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_apt_package_name: "{{ docker_version }}~{{ docker_edition }}~3-0~{{ ansible_distribution | lower }}"

image_versions:
  certbot: 'v0.40.1'
  dovecot: '2019121301'
  postfix: '2019121301'
dovecot_config_dir: '/config/dovecot'
postfix_config_dir: '/config/postfix'
