---
- name: Restart SSH
  ansible.builtin.systemd:
    name: sshd.service
    state: restarted

- name: Restart Fluent Bit
  ansible.builtin.systemd:
    name: fluent-bit.service
    state: restarted
