global:
  scrape_interval:     30s
  evaluation_interval: 30s
  scrape_timeout:      5s

  external_labels:
    monitor: 'home-monitor'

rule_files:
  - 'node.rules'
  - 'prober.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['10.6.0.8:9093']

scrape_configs:
  - job_name: 'router'
    static_configs:
      - targets: ['192.168.101.1:9100']
        labels:
          host: router

  - job_name: 'node'
    static_configs:
      - targets: ['10.6.0.1:9100']
        labels:
          host: hedwig

  - job_name: 'smartmouse'
    metrics_path: '/probe'
    params:
      module: ['http_head']
      target: ['https://smartmousetravel.com/']
    static_configs:
      - targets: ['10.6.0.6:9115']
