- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: '../ansible/roles/docker-server'
    - role: '../ansible/roles/consul-node'
      vars:
        consul_storage_directory: /storage/cluster/consul
    - houseserver
