- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: "../ansible/roles/docker-server"
    - role: "../ansible/roles/consul-node"
      vars:
        consul_config_template: "./config/consul.hcl"
        consul_storage_directory: "/var/consul"
    - role: "../ansible/roles/nomad-node"
      vars:
        nomad_storage_directory: /var/nomad
    - role: "../ansible/roles/vault-node"
      vars:
        vault_storage_consul: true
        vault_unseal_gcpckms: true
        vault_unseal_gcpckms_project: "bergmans-services"
        vault_unseal_gcpckms_key_ring: "vault-home"
    - houseserver
