- name: hostname
  shell: 'hostname --file /etc/hostname'

- name: enable letsencrypt gencerts
  systemd:
    name: gencerts.service
    daemon_reload: yes
    enabled: yes

- name: enable letsencrypt gencerts timer
  systemd:
    name: gencerts.timer
    daemon_reload: yes
    state: started
    enabled: yes

- name: enable consulbackup
  systemd:
    name: consulbackup.service
    daemon_reload: yes
    enabled: yes

- name: enable consulbackup timer
  systemd:
    name: consulbackup.timer
    daemon_reload: yes
    state: started
    enabled: yes
