---
- name: Provision base host requirements
  hosts: all
  roles:
    - base
    - letsencrypt

- name: Provision all-purpose cloud server
  hosts: cloud_all_purpose
  roles:
    - mail_server
    - matrix_server
    - monitoring
    - mumble_server
