---
- name: Provision base host requirements
  hosts: all
  roles:
    - base
    - letsencrypt

- name: Provision all-purpose cloud server
  hosts: cloud_all_purpose
  roles:
    - mail_server
    - matrix_server
    - monitoring
    - mumble_server

- name: Special tasks for snowball
  hosts: snowball.bergmans.us
  handlers:
    - name: Restart Prometheus
      ansible.builtin.systemd:
        name: prometheus.service
        state: restarted
  tasks:
    - name: Run special tasks for snowball
      import_tasks: tasks/snowball/main.yml
