- name: Get HashiCorp upstream APT GPG key
  ansible.builtin.apt_key:
    id: '{{ hashicorp_apt_key }}'
    url: 'https://apt.releases.hashicorp.com/gpg'
    state: present

- name: Configure HashiCorp upstream APT repository
  ansible.builtin.apt_repository:
    repo: '{{ hashicorp_repository }}'
    state: present

- name: Install Vault
  ansible.builtin.apt:
    pkg: ['vault']

- name: Install Vault config
  template:
    src: 'vault.hcl'
    dest: '/etc/vault.d/vault.hcl'
    owner: vault
    group: vault
  notify: ['restart vault']
