# TODO: Generate more SES bits declaratively
#
# The vast majority of this was generated by clicking around in the console,
# including a generated IAM role account and its generated SMTP credentials that
# only appear in Postfix config files.

resource "aws_ses_domain_identity" "bergmanhouse" {
  domain = "bergman.house"
}

resource "google_dns_record_set" "bergmanhouse_ses_dkim1" {
  managed_zone = google_dns_managed_zone.bergmanhouse.name
  name         = "yxm7hu67gktysuirrw3hunu36wxdqz4z._domainkey.bergman.house."
  type         = "CNAME"
  rrdatas      = ["yxm7hu67gktysuirrw3hunu36wxdqz4z.dkim.amazonses.com."]
  ttl          = 3600
}

resource "google_dns_record_set" "bergmanhouse_ses_dkim2" {
  managed_zone = google_dns_managed_zone.bergmanhouse.name
  name         = "e6cvp6jh526bwbemns3obiyexos4mqpl._domainkey.bergman.house."
  type         = "CNAME"
  rrdatas      = ["e6cvp6jh526bwbemns3obiyexos4mqpl.dkim.amazonses.com."]
  ttl          = 3600
}

resource "google_dns_record_set" "bergmanhouse_ses_dkim3" {
  managed_zone = google_dns_managed_zone.bergmanhouse.name
  name         = "deiupgq5gemqwi22la47agp55klxy6j6._domainkey.bergman.house."
  type         = "CNAME"
  rrdatas      = ["deiupgq5gemqwi22la47agp55klxy6j6.dkim.amazonses.com."]
  ttl          = 3600
}
