---
- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: restarted

- name: Restart Prometheus alert manager
  ansible.builtin.systemd:
    name: prometheus-alertmanager.service
    state: restarted
