---
- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: restarted

- name: Restart Prometheus blackbox exporter
  ansible.builtin.systemd:
    name: prometheus-blackbox-exporter.service
    state: restarted

- name: Restart Prometheus alert manager
  ansible.builtin.systemd:
    name: prometheus-alertmanager.service
    state: restarted

- name: Restart Grafana
  ansible.builtin.systemd:
    name: grafana-server.service
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: reloaded
