#!/bin/bash
set -e

hosts=(
    {{ inventory_hostname }}
    mumble.bergmans.us
    blurt.chat
)

for host in ${hosts[@]}; do
  docker run --rm                                               \
     --mount type=volume,source=tls,dst=/etc/letsencrypt        \
     --mount type=bind,source=/var/www/html,dst=/webroot        \
     certbot/certbot:{{ image_versions["certbot"] }} certonly   \
     --non-interactive                                          \
     --agree-tos                                                \
     --email lucas@bergmans.us                                  \
     --keep-until-expiring                                      \
     --webroot                                                  \
     --webroot-path /webroot                                    \
     --domain ${host}
done
