---
- name: Create certbot config directory
  ansible.builtin.file:
    dest: "{{ letsencrypt_config_path }}"
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Install certbot config file
  ansible.builtin.template:
    src: letsencrypt_cli.ini
    dest: "{{ letsencrypt_config_path }}/cli.ini"
    owner: root
    group: root
    mode: "0644"

- name: Link /etc/letsencrypt to certbot config directory
  ansible.builtin.file:
    src: "{{ letsencrypt_config_path }}"
    dest: /etc/letsencrypt
    owner: root
    group: root
    state: link
  when: letsencrypt_config_path != '/etc/letsencrypt'

- name: Install certbot
  ansible.builtin.apt:
    pkg:
      - certbot
      - python3-certbot-dns-google
    state: present

# Currently, the certbot apt package installs a systemd service and timer by
# default. This is just here to check that that behavior doesn't change.
- name: Make sure certbot systemd service is enabled
  ansible.builtin.systemd:
    name: certbot.service
    enabled: yes

- name: Install initial certificates
  ansible.builtin.command:
    argv:
      - /usr/bin/certbot
      - certonly
      - --non-interactive
      - --domain
      - "{{ item }}"
    creates: "{{ letsencrypt_config_path }}/live/{{ item }}/fullchain.pem"
  loop: "{{ letsencrypt_domains }}"
