##############################
# Configure networking and basic stats collection
##############################

- name: Set up static address and networking
  when: is_production|bool
  block:
    - name: Find default netplan config
      find:
        paths: '/etc/netplan'
        patterns: '[0-9]*'
      register: default_netplan_config

    - name: Remove default netplan config
      file:
        path: '{{ item.path }}'
        state: absent
      with_items: '{{ default_netplan_config.files }}'

    - name: Install netplan config
      copy:
        src: netplan.yml
        dest: /etc/netplan/netplan.yaml
        owner: root
        group: root
        mode: '644'

    - name: Write hostname file
      template:
        src: hostname
        dest: /etc/hostname
        mode: '0644'
      notify: hostname

- name: Install node-exporter
  apt:
    pkg:
      - 'prometheus-node-exporter'

##############################
# Configure server storage
##############################

- name: Install ZFS Ubuntu support
  when: is_production|bool
  apt:
    name:
      - zfs-dkms
      - zfsutils-linux

- name: Make storage root
  file:
    path: /storage
    state: directory
    owner: root
    group: root
    mode: '755'

##############################
# Set up Vault unseal and Nomad-to-Vault connection
##############################

- name: Install Vault GCP credentials
  copy:
    src: vaultcreds.json
    dest: /etc/vault.d/creds.json
    mode: '0640'
    owner: vault
    group: vault

- name: Install Nomad Vault config
  copy:
    src: nomadvault.hcl
    dest: /etc/nomad.d/vault.hcl
    mode: '0640'
    owner: nomad
    group: nomad

##############################
# Configure letsencrypt support
##############################

- name: Make directory for crypto material
  file:
    path: /storage/tls
    state: directory
    owner: root
    group: www-data
    mode: '2750'

- name: Install letsencrypt renewal script
  copy:
    src: letsencrypt/gencerts
    dest: /usr/local/sbin
    mode: '750'

- name: Install letsencrypt renewal script systemd service
  copy:
    src: letsencrypt/gencerts.service
    dest: /etc/systemd/system
    mode: '644'
  notify:
    - 'enable letsencrypt gencerts'

- name: Install letsencrypt renewal script systemd timer
  copy:
    src: letsencrypt/gencerts.timer
    dest: /etc/systemd/system
    mode: '644'
  notify:
    - 'enable letsencrypt gencerts timer'

##############################
# Turn on prometheus
##############################

- name: Make prometheus storage directory
  file:
    path: /storage/cluster/prometheus
    state: directory
    owner: nobody
    group: nogroup
    mode: '750'

- name: Make prometheus config directory
  file:
    path: /config/prometheus
    state: directory
    owner: root
    group: adm
    mode: '751'

- name: Make alertmanager storage directory
  file:
    path: /storage/alertmanager
    state: directory
    owner: nobody
    group: nogroup  # alertmanager is hard-coded to run as nobody:nogroup
    mode: '750'

- name: Install alertmanager config
  copy:
    src: prometheus/alertmanager.yml
    dest: /config/prometheus
    owner: root
    group: nogroup  # alertmanager is hard-coded to run as nobody:nogroup
    mode: '640'

##############################
# Turn on grafana
##############################

- name: Make grafana storage directory
  file:
    path: /storage/cluster/grafana
    state: directory
    owner: '472'
    group: '472'  # Ew, fix this UID/GID
    mode: '750'

##############################
# Turn on matrix/synapse
##############################

- name: Create matrix server group
  group:
    name: matrix
    state: present
    system: true

- name: Create matrix server user
  user:
    name: matrix
    group: matrix
    groups: ['www-data']
    create_home: false
    password_lock: true
    system: true
    home: /storage/matrix

- name: Make matrix server storage directory
  file:
    path: /storage/matrix
    state: directory
    owner: matrix
    group: matrix
    mode: '700'

- name: Install matrix server config
  copy:
    src: synapse.yml
    dest: /storage/matrix/homeserver.yaml
    owner: matrix
    group: matrix
    mode: '600'

##############################
# Turn on Plex
##############################

- name: Create video server group
  group:
    name: idiotbox
    state: present
    system: true

- name: Create video server user
  user:
    name: idiotbox
    group: idiotbox
    create_home: false
    password_lock: true
    system: true
    home: /storage/media/plex

- name: Make video server storage directory
  file:
    path: /storage/media/plex
    state: directory
    owner: idiotbox
    group: idiotbox
    mode: '2775'

- name: Make video server work directories
  file:
    path: /storage/media/{{ item }}
    state: directory
    owner: idiotbox
    group: idiotbox
    mode: '2770'
  with_items:
    - 'plex-system'
    - 'plex-transcode'

##############################
# Turn on Moneydance VNC server
##############################

- name: Create Moneydance group
  group:
    name: moneydance
    state: present

- name: Create Moneydance user
  user:
    name: moneydance
    group: moneydance
    create_home: false
    password_lock: true
    home: /storage/users/moneydance

- name: Make Moneydance storage directory
  file:
    path: /storage/users/moneydance
    state: directory
    owner: moneydance
    group: moneydance
    mode: '2770'

##############################
# Turn on Unifi controller
##############################

- name: Create unifi group
  group:
    name: unifi
    state: present

- name: Create unifi user
  user:
    name: unifi
    group: unifi
    create_home: false
    password_lock: true
    home: /storage/unifi

- name: Make unifi storage directory
  file:
    path: /storage/unifi
    state: directory
    owner: unifi
    group: unifi
    mode: '2770'

- name: Make unifi config directory
  file:
    path: '/storage/unifi/data/sites/{{ unifi_site_name }}'
    state: directory
    owner: unifi
    group: unifi
    mode: '2770'

- name: Install unifi gateway config
  copy:
    src: 'usg-config.json'
    dest: '/storage/unifi/data/sites/{{ unifi_site_name}}/config.gateway.json'
    owner: unifi
    group: unifi
    mode: '640'

##############################
# Set up Home Assistant storage
##############################

- name: Make Home Assistant storage directory
  file:
    path: /storage/homeassistant
    state: directory
    owner: root
    group: adm
    mode: '750'

##############################
# Gather user/group data
##############################

# It's a hack that we gather getent at this stage; we're counting on
# only using it for these environment variables and not above

- name: Get user database
  getent:
    database: passwd

- name: Get group database
  getent:
    database: group

- name: Install Moneydance environment config
  template:
    src: moneydance.env
    dest: /config/
    owner: root
    group: adm
    mode: '640'

- name: Install Plex environment config
  template:
    src: plex.env
    dest: /config/
    owner: root
    group: adm
    mode: '640'

- name: Install Synapse environment config
  template:
    src: synapse.env
    dest: /config/
    owner: root
    group: adm
    mode: '640'

- name: Install Unifi environment config
  template:
    src: unifi.env
    dest: /config/
    owner: root
    group: adm
    mode: '640'
