- name: enable nomad
  systemd:
    name: nomad.service
    daemon_reload: yes
    enabled: yes

- name: restart nomad
  systemd:
    name: nomad.service
    state: restarted
  when: nomad_should_start | bool
