- name: Get HashiCorp upstream APT GPG key
  ansible.builtin.apt_key:
    id: '{{ hashicorp_apt_key }}'
    url: 'https://apt.releases.hashicorp.com/gpg'
    state: present

- name: Configure HashiCorp upstream APT repository
  ansible.builtin.apt_repository:
    repo: '{{ hashicorp_repository }}'
    state: present

- name: Install Nomad
  ansible.builtin.apt:
    pkg: ['nomad']

- name: Create Nomad data directory
  file:
    path: '{{ nomad_storage_directory }}'
    state: directory
    owner: nomad
    group: nomad
    mode: '0750'

- name: Install Nomad server config
  template:
    src: nomad.hcl
    dest: /etc/nomad.d/
    owner: nomad
    group: nomad
    mode: '640'
  notify:
    - 'restart nomad'
