- name: Get HashiCorp upstream APT GPG key
  apt_key:
    id: '{{ hashicorp_apt_key }}'
    keyserver: 'hkp://pool.sks-keyservers.net'
    state: present

- name: Configure HashiCorp upstream APT repository
  apt_repository:
    repo: '{{ hashicorp_repository }}'
    state: present

- name: Install Nomad
  apt:
    pkg: ['nomad']

- name: Create Nomad data directory
  file:
    path: '{{ nomad_storage_directory }}'
    state: directory
    owner: nomad
    group: nomad
    mode: '0750'

- name: Install Nomad server config
  template:
    src: nomad.hcl
    dest: /etc/nomad.d/
    owner: nomad
    group: nomad
    mode: '640'
  notify:
    - 'restart nomad'
